name: Latex Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: resume
          root_file: "*.tex"
          glob_root_file: true
      - name: push build artifact
        run: |
          git config user.name Joe-Degs
          git config user.email jpedegs8990@gmail.com
          git branch resume && git switch resume
          find . -type f -name *.pdf -exec git add {} \;
          git commit -m "add build artifact"
          git push -u origin resume
