name: Latex Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: resume
          root_file: "*.tex"
          glob_root_file: true

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume.pdf
          path: "*.pdf"

  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_upload]
    steps:
      - name: Download PDF from artifact store 
        uses: actions/download-artifact@v3
        with:
          name: resume.pdf 
      - name: push artifact back to repo
        uses: hisasann/simple-github-auto-push@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH_NAME: resume
